import { prisma } from "@/lib/prisma";
import Image from "next/image";
import { useParams } from "next/navigation";
import React from "react";
import type { Metadata } from "next";

interface PostdetailsPageProps {
  params: {
    id: string;
  };
}

const fetchProject = async (id: string) => {
  try {
    const project = await prisma.project.findUnique({
      where: { id: id },
    });
    return project;
  } catch (error: unknown) {
    console.log(error);
  }
};

export const generateMetadata = async ({
  params: { id },
}: PostdetailsPageProps): Promise<Metadata> => {
  const project = await fetchProject(id);
  if (project) {
    return {
      title: `Leye | ${project.title} `,
      description: "Project details page",
    };
  } else {
    return {
      title: `Project details `,
      description: "Generated by create next app",
    };
  }
};

const ProjectDeialtPage = async ({ params: { id } }: PostdetailsPageProps) => {
  // const project = await prisma.project.findUnique({
  //   where: { id: id },
  // });
  const project = await fetchProject(id);
  return (
    <div className="w-full mt-[100px]">
      <div className="w-[83%] mx-auto">
        <div className="project-image p-0 md:p-6 lg:h-[470px] lg:w-[70%]">
          {project && (
            <Image
              src={project.image}
              alt="Project Image"
              width={500}
              height={400}
              className="h-full w-full"
            />
          )}
        </div>

        <div className="content lg:w-[70%] p-0 md:p-6">
          <h1 className="text-2xl font-bold text-gray-300 my-6 text-heading3-bold">
            {project?.title}
          </h1>
          {project && (
            <div
              className="text-gray-300 text-justify"
              dangerouslySetInnerHTML={{ __html: project?.body }}
            />
          )}
        </div>
      </div>
    </div>
  );
};

export default ProjectDeialtPage;
